### ISSUE TITLE
Using KeyPress-OSD with OBS Studio Window Capture

### ISSUE THREAD

**Issue by tamas-ferenci** [marius-sucan/KeyPress-OSD#23] opened 2022-04-19 09:42 UTC
Is it possible to use KeyPress-OSD with OBS Studio when using Window Capture mode (i.e., not Display Capture)? With the default configuration OSD is not seem to be recorded with Window Capture.

**Comment by marius-sucan** [comment] 2022-04-19 12:25
Hello!

Thank you for the message.

I'm aware of the problem. It's caused by.... OBS only lists visible windows, and the KeyPress OSD window is automatically hidden.

There is no solution available yet. You may try to have KeyPress OSD hold visible for a long time until you setup OBS. 


Best regards, Marius.

**Comment by marius-sucan** [comment] 2023-03-02 16:21
Hello again!

Full compatibility with OBS is now implemented in v4.68. 

I will close this issue. Thank you again for the suggestions.

Best regards, Marius.

**Closed by marius-sucan** 2023-03-02 16:21 UTC
